### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by Hegezcc** [BeYkeRYkt/LightAPI#10]
Are there any plans for Maven support? It would make this a lot easier to build.

**Comment by Hegezcc** [comment]
Also any build instructions would make it even possible.

**Comment by To-mos** [comment]
I wrote a custom POM file that compiled Successfully on (8/2/2017) [here](https://pastebin.com/t8fWq37u).

Create a pom.xml file in the project folder next to the README.md file.
Open CMD and locate the folder.
Type in "mvn install" and if all works you should get "BUILD SUCCESS" in all green.
It worked for me at the time of posting this.

Edit: it appears that it cannot locate the correct files to compile correctly resulting in a jar file full of .java files. I'll be messing with this as I go along. Will report back if I REALLY get it working.

It appears that it wants:
craftbukkit_v1_10_R1.jar
craftbukkit_v1_11_R1.jar
craftbukkit_v1_12_R1.jar
craftbukkit_v1_8_R1.jar
craftbukkit_v1_9_R1.jar
craftbukkit_v1_9_R2.jar
They will have to be provided before it will happily compile. I believe you can run BuildTools.jar to generate them.

**Comment by Hegezcc** [comment]
Thank you!
