### ISSUE TITLE
adding as dependency with maven/gradle

### ISSUE THREAD

**Issue by user5145** [BeYkeRYkt/LightAPI#12]
It would be helpful to add mvn/gradle support for compatibility with jitpack or even add the project to e. g. maven repo. Or any information about how to use it with maven/gradle to the description or wiki because i want to use it with gradle and i don't know how.

edit: typo
edit2: putting the jar to a local maven repo seems to be the best what can be done to speed up building of packages which depend on it.

for compileOnly group: 'custom', name: 'LightAPI', version:'3.2.4 X.12.1'
it would be /home/$USER/.m2/repository/custom/LightAPI/3.2.4 X.12.1/LightAPI-3.2.4 X.12.1.jar and it should take the jar automatically.

edit3: i'm not interested anymore

**Comment by Qveshn** [comment]
Yes I agree. Author has lost interest in minecraft. His Last message:
https://github.com/BeYkeRYkt/LightAPI/releases

Therefore, now I am trying to support plugin.
This is my fork of LightAPI:
github: https://github.com/Qveshn/LightAPI
spigot: https://www.spigotmc.org/resources/lightapi-fork.48247/
I will try to add maven and/or gradle to it, but I'm new to them. So, it takes me a long time to do it correctly.

Thanks =)

**Comment by user5145** [comment]
I've been trying to do it and i gave up because of those 2 problems:

1. i wasn't able to build org.bukkit.craftbukkit.v1_8_R3 and v1_9_R2 so i have never built this project

2. lightapi is backward compatible with old minecraft versions.

Normally to build something what can use a few versions of the same library one uses osgi (but it cannot be done here because it requires a special environment to run). Gradle and maven disallow (as i remember) to load different org.bukkit.craftbukkit dependencies. To build it it may be necessary to build a different version of lightapi for every minecraft version.

I was searching on the internet, and i found something about a gradle feature called tasks. I think it can be used to keep the backward compatibility and still build it using gradle. My idea was to run tasks one after another and they would do something like this

start task 1 -> compile everything except things related to craftbukkit -> 
start task 2 -> load v1_8_R3 -> compile everything related to v1_8_R3 -> unload v1_8_R3 ->
start task 3 -> load v1_9_R1 -> compile everything related to v1_9_R1 -> unload v1_9_R1 ->
etc

edit: i misspelled "build"...
edit2: could you tell me on what i should focus to learn minecraft modding better? i'm mainly interested in nms and in the past i've been learning only about java based servers (spring, jsf, hibernate, linux). i don't think i can help you now because im not skilled enough.

**Comment by Qveshn** [comment]
Hello
I can tell you how I configured my IDE to build this project. This is not hard. Now I build project for all version with "one click".
I use intellij idea (https://www.jetbrains.com/idea/). I've created idea project from scratch. 
All I needed - it is to download all required libraries (all required spigot versions and so on) and to make references to them.
I did it in intellij idea, but I think it is also easy to do in eclipse and other ide.
So, if you want, I can tell in detail how to make project from scratch to build final jar file with "one click"
In any case I suggest you to use my fork, because it has new updates.

=)

**Comment by user5145** [comment]
Hi
sure, if that's not a problem for you :)
I use eclipse (it's cheaper), but i have been using intellij too.
Now i'm busy with studies and i put all my time to build flatpak versions of every application i use. But i will dig into it when i find a while.
is it fine to write here?
