### ISSUE TITLE
Conflict of QualityArmor

### ISSUE THREAD

**Issue by spruill7716** [BeYkeRYkt/LightAPI#14]
Updated to the latest version of QualityArmor and LightAPI with 1.14 support. Whenever I try and use a gun on an entity, the server spams:

[15:01:12] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Willy_Donka moved too quickly! -3.9195018459594007,0.0,9.409420384974396

Then is followed by this crash:
https://www.dropbox.com/s/32l3weba52oouyi/GunCrash.txt?dl=0

Just by glancing over the text, I see mentions of both "guns" and the LightAPI plugin. Could this be some sort of conflict? I posted a similar issue on the QA page as well.

**Comment by spruill7716** [comment]
EDIT: Found another issue when utilizing the Street Lamp with FurnitureLib.

Crash: https://www.dropbox.com/s/i41jkrobxcsh8ba/CrashFurni.txt?dl=0

**Comment by BeYkeRYkt** [comment]
Try: https://www.dropbox.com/s/wxh3o69q4h73qda/LightAPI.jar?dl=0
