### ISSUE TITLE
Plugins can't find Light api

### ISSUE THREAD

**Issue by IPECTER** [BeYkeRYkt/LightAPI#19]
Plugins can't find Light api.
But I think Light api work well.

**Comment by BeYkeRYkt** [comment]
What plugins are you using?

**Comment by IPECTER** [comment]
Itemadder (this plugin need new update because It disable LightAPI)

Aurora (can't find LightAPI)
![image](https://user-images.githubusercontent.com/80433772/138032577-0425c094-e226-42db-b011-238e48e58f4c.png)

**Comment by BeYkeRYkt** [comment]
> Aurora (can't find LightAPI)

This happens because Aurora itself disables this feature.
https://github.com/OpticFusion1/Aurora/blob/master/src/main/java/com/zenya/aurora/util/ext/LightAPI.java#L91

**Comment by OpticFusion1** [comment]
This is because StarLight is used and unsupported, removing it will just cause errors in console

**Comment by IPECTER** [comment]
oh, Can you update Aurora?

**Comment by IPECTER** [comment]
> This is because StarLight is used and unsupported, removing it will just cause errors in console

oh, Can you update Aurora?

**Comment by OpticFusion1** [comment]
I can't update until LightAPI supports StarLight

**Comment by IPECTER** [comment]
> I can't update until LightAPI supports StarLight

https://www.spigotmc.org/resources/lightapi.4510/updates

**Comment by OpticFusion1** [comment]
Although I've said this in my support server, I'll say it here as well.
Aurora's LightAPI dependency won't be updated until there's a STABLE build out, as of now it's either not supported or just a preview build

**Comment by IPECTER** [comment]
@BeYkeRYkt 
When do you think you will be able to complete the stable version?
There are a lot of things that I need to use LightAPI.
So, I need to set my server opening date close to the stable release date of LightAPI.

and Why dont you make your discord server?

**Comment by BeYkeRYkt** [comment]
> When do you think you will be able to complete the stable version?

When will [Valve time](https://www.urbandictionary.com/define.php?term=Valve%20Time) come
![изображение](https://user-images.githubusercontent.com/2690323/138076994-c91860ad-ed92-41ae-a791-3248dd724299.png)


> Why dont you make your discord server?

There's no need for that.
