### ISSUE TITLE
Not working on papers latest builds

### ISSUE THREAD

**Issue by Boy0000** [BeYkeRYkt/LightAPI#20]
Probably not unknown to you, but figured I would mention it.

Trying to set light does nothing, and whenever i getLightLevel it returns -11
![image](https://user-images.githubusercontent.com/62521371/139663594-36a7472d-77b1-4520-99ff-786621154cf4.png)

It also returns -11 even when im not setting and just getting the lightlevel

Not sure if im the one doing it wrong or if its just not fully working for Papers Tuinity merge just yet

**Comment by BeYkeRYkt** [comment]
I'm not sure, but there are some comments:
1. Do not call LightAPI.initialization(). It is intended for internal use.
2. The lighting level may not change if the current lighting level is brighter than the required one.
3. Use [ResultCodes](https://github.com/BeYkeRYkt/LightAPI/blob/5.0/common/src/main/java/ru/beykerykt/minecraft/lightapi/common/api/ResultCode.java). The setLightLevel/getlightlevel methods can return the execution code from this list.
4. I'm not sure, but it seems broadcastVal shows the value of "location.blockZ".

For example:

```
        int blockLight = LightAPI.get().getLightLevel(worldName, blockX, blockY, blockZ, LightFlag.BLOCK_LIGHTING);
        broadcastMessage("LightLevel: " + blockLight);
        int resultCode = LightAPI.get().setLightLevel(worldName, blockX, blockY, blockZ, lightLevel);
        switch (resultCode) {
            case ResultCode.SUCCESS:
                // The request was executed.
                break;
            case ResultCode.MOVED_TO_DEFERRED:
                // The request has been moved to the queue and will be executed after a while.
                break;
            default:
                broadcastMessage("Something is wrong. Result code:" + resultCode);
                break;
        }
```

**Comment by Boy0000** [comment]
![image](https://user-images.githubusercontent.com/62521371/139669649-cd366f75-8493-4023-a1c0-677e75d9873a.png)
![image](https://user-images.githubusercontent.com/62521371/139669669-e93539e4-7a7c-4171-86f4-65a0bffc17d5.png)
light where im standing is 0 sky 0 block
 its Kotlin btw hence when lol

**Comment by BeYkeRYkt** [comment]
Check the name of the world. Code -2 means that the world is unavailable.

**Comment by Boy0000** [comment]
Yeah seems location.world.tostring was CraftWorld(name=world) so makes sense why it didnt work.
Works after fixing this to be the actual worldname, though i had to hardcode it to the stringname, as world doesnt use Location but takes a string..

**Comment by PatrickMSM** [comment]
Please close this issue if your issue was fixed.
