### ISSUE TITLE
Proper API release and documentation

### ISSUE THREAD

**Issue by Andre601** [BeYkeRYkt/LightAPI#21]
The v5 release of LightAPI is nice, but lacks a lot of things such as proper API documentation.

There is no way for devs to know how they can add the API as a dependency, and directly including the jar into your project isn't really something evrryone want to or even can do.

That and the lack of a migration guide makes this unreasonably difficult.

**Comment by Andre601** [comment]
Something else that was pointed out to me is, that the plugin seems to rely on and use jar dependencies including PaperMC itself.

This is questionable, as it may or may not be a possible violation of licenses and/or Mojangs EULA as you could see it as a possible re-distribution of their Server code which is not tolerated by them... But this is not something I can or will prove here.

So tl;dr: Please use a proper dependency management with repository and dependency setups...

**Comment by LoneDev6** [comment]
Same concerns

**Comment by BeYkeRYkt** [comment]
> The v5 release of LightAPI is nice, but lacks a lot of things such as proper API documentation.

And what kind of documentation do you want to get ? The functions available to you are described on the page in [spigotmc.org](https://www.spigotmc.org/resources/lightapi.4510/). The only difference is that you don't have to worry about sending packets. If you need documentation about the internal kitchen of the plugin, then there will be no such information in the near future.

> There is no way for devs to know how they can add the API as a dependency, and directly including the jar into your project isn't really something evrryone want to or even can do.

Unfortunately I don't have the ability to provide a maven repository, but you can use jitpack.io if you need it. Initially, it is assumed that the user has the ability to connect the maven repository or connect jar files to the project.

> Something else that was pointed out to me is, that the plugin seems to rely on and use jar dependencies including PaperMC itself.

We use jar libraries only to compile 'craftbukkit-nms-*' modules and do not distribute them. SpigotMC/PaperMC dependencies are built using BuildTools, distributed via [spigotmc.org](https://hub.spigotmc.org/jenkins/job/BuildTools/) or compilated from [PaperMC](https://github.com/PaperMC/Paper). Dependencies are stored locally on the computer where the build was made.
We are recreating some Starlight engine code using Java Reflection to be able to change the lighting levels inside Starlight. Without the use of these hacks, changing the lighting levels is not possible.

**Comment by Andre601** [comment]
> And what kind of documentation do you want to get ? The functions available to you are described on the page in [spigotmc.org](https://www.spigotmc.org/resources/lightapi.4510/). The only difference is that you don't have to worry about sending packets. If you need documentation about the internal kitchen of the plugin, then there will be no such information in the near future.

I guess that's something. My concern was more about the fact that you mentioned that the API was recoded, but didn't mention what has changed compared to the previous API, keeping devs in the dark.

> Unfortunately I don't have the ability to provide a maven repository, but you can use jitpack.io if you need it. Initially, it is assumed that the user has the ability to connect the maven repository or connect jar files to the project.

There are services like CodeMC.io that could give you access to a maven repo to upload the API on. It just requires a join request and approval of it.

> We use jar libraries only to compile 'craftbukkit-nms-*' modules and do not distribute them. SpigotMC/PaperMC dependencies are built using BuildTools, distributed via [spigotmc.org](https://hub.spigotmc.org/jenkins/job/BuildTools/) or compilated from [PaperMC](https://github.com/PaperMC/Paper). Dependencies are stored locally on the computer where the build was made. We are recreating some Starlight engine code using Java Reflection to be able to change the lighting levels inside Starlight. Without the use of these hacks, changing the lighting levels is not possible.

okay.

**Comment by LoneDev6** [comment]
@BeYkeRYkt Thanks for your hard work!

The important thing is that you are sure about the fact that you won't recode the API again. I have to be sure that I can use the API without the need to update my implementation in the future.

**Comment by BeYkeRYkt** [comment]
> 
> 
> @BeYkeRYkt Thanks for your hard work!
> 
> The important thing is that you are sure about the fact that you won't recode the API again. I have to be sure that I can use the API without the need to update my implementation in the future.

I can't give you a 100% guarantee on this, since the pieces of the plugin may still be recoded in the future. But I tried to reduce the impact by dividing packages into 'api' and 'internal'. If you want to get maximum compatibility, then use [LightAPI.get()](https://github.com/BeYkeRYkt/LightAPI/blob/5.0/common/src/main/java/ru/beykerykt/minecraft/lightapi/common/LightAPI.java), keep track of the versions in [Build](https://github.com/BeYkeRYkt/LightAPI/blob/5.0/common/src/main/java/ru/beykerykt/minecraft/lightapi/common/Build.java) and do not use the 'internal' package. If a situation happens in the future when full recoding is needed, then I will try to make a '[backward](https://github.com/BeYkeRYkt/LightAPI/tree/5.0/bukkit-backward-support)' module as in the current implementation.

**Comment by LoneDev6** [comment]
I can confirm the API works fine on 1.17.1, I'm very satisfied with that!
Tested on Spigot 1.17.1 and Paper 1.17.1.

Good job!

I suggest you to ask the developer of the LightAPI Fork to add a big red button to download your updated API.
https://www.spigotmc.org/resources/lightapi-fork.48247/
