### ISSUE TITLE
Can you register this api on "maven"?

### ISSUE THREAD

**Issue by IPECTER** [BeYkeRYkt/LightAPI#22]
Can you register this api on "maven"?
There are many projects that need to use this API through Maven.
If the registration is completed, can you tell me groupId, artifactId, and version?

It might sound weird because i use a translator.

**Comment by WaIaF** [comment]
bump

**Comment by flashpaul** [comment]
Also me need this!

**Comment by BeYkeRYkt** [comment]
Use JitPack: https://jitpack.io/#BeYkeRYkt/LightAPI
