### ISSUE TITLE
What is the new way to do LightAPI.collectChunks and get players inside?

### ISSUE THREAD

**Issue by gartia** [BeYkeRYkt/LightAPI#24]

**Comment by gartia** [comment]
LightAPI.collectChunks(this.lastWorld,this.lastBlockX,this.lastBlockY,this.lastBlockZ,this.lightType,this.lightLevel);
Collection<? extends Player> players = info.get(0).getReceivers();

Was the old way

**Comment by BeYkeRYkt** [comment]
In 5.0 version, you do not need to manually send packets to players, plugin will do it itself.
Also in this version, you can no longer send packets to certain players, due to synchronization issues.

But if there is a need, you can use the following code:
```
IBukkitExtension bukkitExtension = (IBukkitExtension) LightAPI.get().getExtension();
IHandler handler = bukkitExtension.getHandler();
List<IChunkData> chunkList = handler.collectChunkSections(location.getWorld(), location.getBlockX(),
              location.getBlockY(), location.getBlockZ(), lightLevel == 0 ? blockLightLevel : lightLevel,
              lightType);
for (int i = 0; i < chunkList.size(); i++) {
      IChunkData data = chunkList.get(i);
      handler.sendChunk(data);
}
```

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained. Use LightBlock instead
