### ISSUE TITLE
[BUG] Randomly crash main thread on 1.18.1

### ISSUE THREAD

**Issue by Rothes** [BeYkeRYkt/LightAPI#26]
## Description
LightAPI randomly crashs my server when loading the chunk (I uses Aurora for it, so LightAPI always works). This occurs every about 10 minutes (for one player).

## Thread Dump
1. https://pastebin.ubuntu.com/p/7s6kNMQW6B/
2. https://pastebin.ubuntu.com/p/xgyytynfbV/

## Server Info
**Server**: git-Purpur-1551 *(also tried git-JettPack-425, both is fork of Paper and occurs)*
**Version**: 1.18.1
**Plugins**: Plugins (53): AllMusic, AngelChest, AntiSeedCracker, Aurora, AutoBroadcastLite, BungeeTabListPlus, CMI, CMIEInjector, CMILib, ChanLang, Chunky, CoreProtect, DeluxeMenus, FPSHelper, FastAsyncWorldEdit, HandItemPapi, InteractionVisualizer, InventoryRollbackPlus, JukeBox, LockettePro, LuckPerms, LightAPI, Matrix, MoneyReward, Multiverse-Core, NeverLag, NoteBlockAPI, Oh_the_dungeons_youll_go, OpenInv, Orebfuscator, PlaceholderAPI, PlaceholderFixer, PlasmoVoice, Prism, ProtocolLib, ProtocolStringReplacer, QuickShop, Residence, RothesPapi, RothesUtils, ServerUtils, Slimefun, Spartan, TeleportCosts, TitleManager, Tweakin, Vault, ViaBackwards, ViaVersion, ViaVersionStatus, WorldGuard, floodgate, mcMMO and spark
* LightAPI v5.1.0 from SpigotMC

**Comment by BeYkeRYkt** [comment]
Sorry, but I can't reproduce the problem. I generated the world by walking around it for 20 minutes and didn't meet anything unusual. I used git-Purpur-1566 and Java 17 2021-09-14 (LTS). 
Plugin List: 
Aurora, InteractionVisualizer, LightAPI, LightTest, QualityArmory, ProtocolLib, ShinyItems and spark

**Comment by Rothes** [comment]
> Sorry, but I can't reproduce the problem. I generated the world by walking around it for 20 minutes and didn't meet anything unusual. I used git-Purpur-1566 and Java 17 2021-09-14 (LTS). Plugin List: Aurora, InteractionVisualizer, LightAPI, LightTest, QualityArmory, ProtocolLib, ShinyItems and spark

Thanks for tracking this issue. I will try it on 1.18.2 this weekend and see if it still can be reproduced.

**Comment by Rothes** [comment]
Cannot reproduce on git-Purpur-1598 (MC: 1.18.2). Closing.
