### ISSUE TITLE
light source is not show

### ISSUE THREAD

**Issue by entonoire** [BeYkeRYkt/LightAPI#28]
Hey, i use that code :

```
int result = LightAPI.get().setLightLevel(light.location.getWorld().getName(), light.type, light.location.getBlockX(), light.location.getBlockY(), light.location.getBlockZ(), light.level, EditPolicy.FORCE_IMMEDIATE, SendPolicy.IMMEDIATE, null);
		
		switch (result) {
		  case ResultCode.SUCCESS:
			  Main.getLog().log(Level.INFO, "Success " + result);
		    break;
		  case ResultCode.MOVED_TO_DEFERRED:
			  Main.getLog().log(Level.INFO, "Light moved " + result);
		    break;
		  default:
		    Main.getLog().log(Level.WARNING, "Something is wrong. Result code: " + result);
		    break;
		}
```

to create a light source but that problem is that it tell me "Success 0" but that light don't show and i have the last version of the plugin.

**Comment by BeYkeRYkt** [comment]
Where are you calling it from ? If you call from BlockPlaceEvent or BlockDestroyEvent, then you need to change the lighting level after one tick.

**Comment by entonoire** [comment]
I call it in a function in an other class who manage every light and after I call this function in a onCommand.

**Comment by BeYkeRYkt** [comment]
Sorry, but I can't reproduce this problem. As a solution, I can suggest using other policies and make sure that there are no changes with blocks around the light source.

**Comment by entonoire** [comment]
You know what i will post my plugin on github with the jar do you can see everything.

**Comment by entonoire** [comment]
https://github.com/entonoire/LightManager/
by the way i'm on spigot 1.16.5

**Comment by BeYkeRYkt** [comment]
You incorrectly used arguments:
You used
`(worldName, lightType, getBlockX(), getBlockY(), getBlockZ(), lightLevel) `
And you need to use
`(worldName, getBlockX(), getBlockY(), getBlockZ(), lightLevel, lightType) `

**Comment by entonoire** [comment]
i think you check the main branch the main code IS with the fork see the old branch

**Comment by BeYkeRYkt** [comment]
No, I was looking at the old code
https://github.com/entonoire/LightManager/blob/old/src/fr/vallfeur/lme/Light.java#L49

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained. Use LightBlock instead
