### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [BeYkeRYkt/LightAPI#3]
logs
http://pastebin.com/asYfgBbX

timings
https://timings.aikar.co/v2/?id=d5a131f5daeb4dbb81e8b853c69c1f81

**Comment by BeYkeRYkt** [comment]
Check [this](https://www.spigotmc.org/threads/plugin-already-initialized-when-reloading-my-plugin-with-plugman-or-any-other-plugin-manager.101079/#post-1102266)
