### ISSUE TITLE
Source is broken and can't resolve dependencies and can't compile.

### ISSUE THREAD

**Issue by Fox2Code** [BeYkeRYkt/LightAPI#32]
I was trying to contribute to LightAPI but I have the following errors:
```
Unresolved dependency: 'io.papermc.paper:paper-server:jar:1.18.2-R0.1-SNAPSHOT'
Unresolved dependency: 'org.spigotmc:spigot-api:jar:1.18.2-R0.1-SNAPSHOT'
```
No documentation on repo is telling that it's intended and/or if there is a fix to this issue.

**Comment by BeYkeRYkt** [comment]
You need to compile the remapped spigot and paper builds
https://www.spigotmc.org/threads/9-years-of-spigotmc-spigot-bungeecord-1-18-1-18-2-release.534760/
https://github.com/PaperMC/Paper

**Comment by Fox2Code** [comment]
Well, I think this should be added in documentation.

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained. Use LightBlock instead
