### ISSUE TITLE
1.19 PLS

### ISSUE THREAD

**Issue by TheExO7** [BeYkeRYkt/LightAPI#33]
I need LightAPI for 1.19 ....
It's going to be 1 month since you said "soon" I can't work without the pl :/

**Comment by VergilPrime** [comment]
It's been 12 days...

**Comment by TheExO7** [comment]
And I've been waiting for 12 days :/
While all the pl who need light api have gone to 1.19 :/

**Comment by Classsic36** [comment]
Patience... it will arrive eventually.

**Comment by GaijinPL** [comment]
Please 1.19 API need ItemsAdder

**Comment by Jok1E** [comment]
1.19 please 1.19 please 1.19 please 1.19 please

**Comment by MelonCraftDE** [comment]
dev isnt active, someone needs to fork it and finish this job

**Comment by sujyrokimora** [comment]
first time looking plugin source so a little help would be nice
![image](https://user-images.githubusercontent.com/37046592/178237309-f5357b83-f701-4c27-b5cb-32c086b837ea.png)
someone knows whats going on
update: the plugin it self is broken??? there files missing

**Comment by MelonCraftDE** [comment]
> first time looking plugin source so a little help would be nice ![image](https://user-images.githubusercontent.com/37046592/178237309-f5357b83-f701-4c27-b5cb-32c086b837ea.png) someone knows whats going on update: the plugin it self is broken??? there files missing

LightAPI is not working with 1.19
i doubt that it ever will work, the dev is inactive.

**Comment by sujyrokimora** [comment]
> > first time looking plugin source so a little help would be nice ![image](https://user-images.githubusercontent.com/37046592/178237309-f5357b83-f701-4c27-b5cb-32c086b837ea.png) someone knows whats going on update: the plugin it self is broken??? there files missing
> 
> LightAPI is not working with 1.19 i doubt that it ever will work, the dev is inactive.

i know im asking the community, i was trying to fix it but plugin dev knowledge is 0

**Comment by Scheaweppes** [comment]
+1 please update 1.19

**Comment by eris-webserv** [comment]
The package is in, so yall can stop complaining now.
If you want I'll fork it and add actions so you can use it now.

**Comment by VergilPrime** [comment]
Thanks Eris :)

**Comment by Chris6ix** [comment]
> The package is in, so yall can stop complaining now. If you want I'll fork it and add actions so you can use it now.

~~That would be great!
I just looked at your fork, and it seems like the build failed :(
Could you please fix it so that we are able to download it from your fork?~~

Edit: It's ok, the Update was finally posted to Spigot. Thanks anyway.

**Comment by Dymeth** [comment]
Updated to 1.19:
https://www.spigotmc.org/resources/lightapi.4510/update?update=465301

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained. Use LightBlock instead
