### ISSUE TITLE
Update for 1.19.3

### ISSUE THREAD

**Issue by TheFaik** [BeYkeRYkt/LightAPI#41]
Please update the plugin to 1.19.3 please.

**Comment by fnrcum** [comment]
i'm willing to pay 100 usd to whomever updates it and uploads a working build

**Comment by ahdg6** [comment]
For anyone want a working jar, please check https://github.com/IPECTER/LighterAPI/releases/tag/5.4.0-SNAPSHOT

**Comment by ahdg6** [comment]
I'm currently experimenting with the new starlight, for any pure spigot user, you can use this jar for 1.19.3.
[LightAPI-spigot-only.jar.zip](https://github.com/BeYkeRYkt/LightAPI/files/10579166/LightAPI-spigot-only.jar.zip)
just remove `.zip`

**Comment by TheStilk** [comment]
> Please update the plugin to 1.19.3 please.

Bro, go to settings and change the settings there:
   enable-compatibility-mode: false
   force-enable-legacy: false
here you change them to true
I will be glad if you give me some money 👉👈

**Comment by ahdg6** [comment]
> > Please update the plugin to 1.19.3 please.
> 
> Bro, go to settings and change the settings there: enable-compatibility-mode: false force-enable-legacy: false here you change them to true I will be glad if you give me some money 👉👈

compatibility-mode use vanilla block to implemente function which it's though to be expensive to hardware.
I'm trying to adapt the latest paper changes to make the LightAPI formally update to 1.19.3.

**Comment by ahdg6** [comment]
Most of the difficulty of the current update comes from https://github.com/PaperMC/Paper/pull/8177 :)

**Comment by ahdg6** [comment]
My current changes don't report errors but won't take effect, and as the paper changes are nearly 2w lines long, it takes a lot of effort to fully understand them, anyone interested in picking up the job can use my code, I've made the whole project much cleaner and compilable.
https://github.com/ahdg6/LightAPI

**Comment by zikehalil3535** [comment]
> My current changes don't report errors but won't take effect, and as the paper changes are nearly 2w lines long, it takes a lot of

Still we cant use for any paper fork?

**Comment by ahdg6** [comment]
If you want to use lightapi without enabling Lagecy mode, then yes

**Comment by ahdg6** [comment]
Struggling with the NMS and internal logic can be very taxing, and it can be hard for anyone who hasn't been exposed to the mechanics of the game's core.

**Comment by IPECTER** [comment]
LightAPI 1.13 ~ 1.19.4 Spigot & Paper
Try this https://github.com/IPECTER/LighterAPI/releases/tag/5.4.0-SNAPSHOT

**Comment by ahdg6** [comment]
wow, you make it, love u >3

**Comment by qualk** [comment]
> LightAPI 1.13 ~ 1.19.4 Spigot & Paper Try this https://github.com/IPECTER/LighterAPI/releases/tag/5.4.0-SNAPSHOT

> i'm willing to pay 100 usd to whomever updates it and uploads a working build

@fnrcum Looks like IPECTER updated it an uploaded a working build.

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained.
