### ISSUE TITLE
LighterAPI —— A fork of LightAPI that supports 1.15.2-1.20.4

### ISSUE THREAD

**Issue by lijinhong11** [BeYkeRYkt/LightAPI#44]
The branch is died 2 years ago, and still no people make a useful and newer branch?  
Here is it.  
The repo address: https://github.com/LinsMinecraftStudio/LighterAPI  
We made a pre-release just 10 mins ago (after the issues submitted).
You can download it can test it, if you get any errors from it, please create issues.
**Warning: 1.20-1.20.4 compatibility still needs tests, please help us**
**Note: we remove backwards-support**

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained.
